In [1]:
import numpy as np

In [3]:
def swap_rows(M, row_index_1, row_index_2):
    
    M = M.copy()
    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]
    return M

In [4]:
M = np.array([
[1, 3, 6],
[0, -5, 2],
[-4, 5, 8]
])
print(M)

[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [5]:
M_swapped = swap_rows(M, 0, 2)
print(M_swapped)

[[-4  5  8]
 [ 0 -5  2]
 [ 1  3  6]]


In [6]:
M[1:,2]

array([2, 8])

In [7]:
def get_index_first_non_zero_value_from_column(M, column, starting_row):
    
    column_array = M[starting_row:,column]
    for i, val in enumerate(column_array):
        if not np.isclose(val, 0, atol = 1e-5):
            index = i + starting_row
            return index
    return -1

In [8]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [9]:
print(get_index_first_non_zero_value_from_column(N, column = 0, starting_row = 0))

-1


In [10]:
print(get_index_first_non_zero_value_from_column(N, column = -1, starting_row = 2))

3


In [11]:
def get_index_first_non_zero_value_from_row(M, row, augmented = False):
    
    M = M.copy()
    if augmented == True:
        M = M[:,:-1]
    row_array = M[row]
    for i, val in enumerate(row_array):
        if not np.isclose(val, 0, atol = 1e-5):
            return i
    return -1

In [12]:
M[2]

array([-4,  5,  8])

In [13]:
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [14]:
N[0,:]

array([ 0,  5, -3,  6,  8])

In [15]:
print(f'Output for row 2: {get_index_first_non_zero_value_from_row(N, 2)}')
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3)}')

Output for row 2: -1
Output for row 3: 4


In [16]:
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3, augmented = True)}')

Output for row 3: -1


In [17]:
def augmented_matrix(A, B):
    
    augmented_M = np.hstack((A,B))
    return augmented_M

In [18]:
A = np.array([[1,2,3], [3,4,5], [4,5,6]])
B = np.array([[1], [5], [7]])
print(augmented_matrix(A,B))

[[1 2 3 1]
 [3 4 5 5]
 [4 5 6 7]]


In [19]:
M.shape

(3, 3)

In [20]:
def row_echelon_form(A, B):
    
    det_A = np.linalg.det(A)
    if np.isclose(det_A, 0) == True:
        return 'Singular system'
    A = A.copy()
    B = B.copy()
    A = A.astype('float64')
    B = B.astype('float64')
    num_rows = len(A) 
    M = augmented_matrix(A,B)
    for row in range(num_rows):
        pivot_candidate = M[row, row]
        if np.isclose(pivot_candidate, 0) == True: 
            first_non_zero_value_below_pivot_candidate = get_index_first_non_zero_value_from_column(M, row, row) 
            M = swap_rows(M, row, first_non_zero_value_below_pivot_candidate) 
            pivot = M[row,row] 
        else:
            pivot = pivot_candidate 
        M[row] = (1/pivot) * M[row]
        for j in range(row + 1, num_rows): 
            value_below_pivot = M[j,row]
            M[j] = M[j] - value_below_pivot*M[row]
    return M

In [21]:
A = np.array([[1,2,3],[0,1,0], [0,0,5]])
B = np.array([[1], [2], [4]])
row_echelon_form(A,B)

array([[1. , 2. , 3. , 1. ],
       [0. , 1. , 0. , 2. ],
       [0. , 0. , 1. , 0.8]])

In [22]:
def back_substitution(M):
    
    M = M.copy()
    num_rows = M.shape[0]
    for row in reversed(range(num_rows)): 
        substitution_row = row
        index = get_index_first_non_zero_value_from_row(M, substitution_row, augmented = True)
        for j in range(row): 
            row_to_reduce = M[j] 
            value = row_to_reduce[index]
            row_to_reduce = row_to_reduce  - (value* M[substitution_row])
            M[j,:] = row_to_reduce
    solution = M[:,-1]
    return solution

In [24]:
def gaussian_elimination(A, B):
    
    row_echelon_M = row_echelon_form(A,B)
    if not isinstance(row_echelon_M, str): 
        solution = back_substitution(row_echelon_M)
    return solution

In [25]:
from utils import string_to_augmented_matrix

In [26]:
equations = """
3*x + 6*y + 6*w + 8*z = 1
5*x + 3*y + 6*w = -10
4*y - 5*w + 8*z = 8
4*w + 8*z = 9
"""
variables, A, B = string_to_augmented_matrix(equations)
sols = gaussian_elimination(A, B)
if not isinstance(sols, str):
    for variable, solution in zip(variables.split(' '),sols):
        print(f"{variable} = {solution:.4f}")
else:
    print(sols)

x = -1.5414
y = -0.5223
w = -0.1210
z = 1.1855
